name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
          
    steps:
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ^1.22.1
        
        - name: Wait for PostgreSQL
          run: |
            until pg_isready -h localhost -p 5433 -U ${{ secrets.POSTGRES_USER }}; do
              echo "$(date) - waiting for database to start"
              sleep 2
            done

        - name: Install golang-migrate
          run: |
            curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
            echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
            sudo apt-get update
            sudo apt-get install -y migrate
            migrate -version

        - name: List DB migration directory content
          run: |
            ls -alh
            ls -alh db/migration/
          

        - name: Database Migration
          run: migrate -path db/migration -database "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}?sslmode=disable" -verbose up
          env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          
        - name: Test
          env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          run: go test -v -cover ./...
          