name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
          
    steps:
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ^1.22.1
        
        - name: Wait for PostgreSQL
          run: |
            until pg_isready -h localhost -p 5433 -U ${{ secrets.POSTGRES_USER }}; do
              echo "$(date) - waiting for database to start"
              sleep 2
            done

        - name: Install golang-migrate
          run: |
            version=v4.14.1
            os=linux
            arch=amd64
            curl -L https://github.com/golang-migrate/migrate/releases/download/${version}/migrate.${os}-${arch}.tar.gz -o migrate.tar.gz
            mkdir -p migrate-extract
            tar -xvzf migrate.tar.gz -C migrate-extract
            sudo mv migrate-extract/migrate /usr/local/bin/migrate
            rm -rf migrate-extract migrate.tar.gz
            migrate -version
          

        - name: Database Migration
          env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          run: migrate -path db/migration -database "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5433/${{ secrets.POSTGRES_DB }}?sslmode=disable" -verbose up
        
        - name: Test
          env:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5433
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          run: go test -v -cover ./...
          